-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 17:08:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema plantDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plantDB` ;

-- -----------------------------------------------------
-- Schema plantDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plantDB` DEFAULT CHARACTER SET utf8 ;
USE `plantDB` ;

-- -----------------------------------------------------
-- Table `plantDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantDB`.`user` ;

CREATE TABLE IF NOT EXISTS `plantDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantDB`.`plant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantDB`.`plant` ;

CREATE TABLE IF NOT EXISTS `plantDB`.`plant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commun_name` VARCHAR(45) NOT NULL,
  `scientific_name` VARCHAR(45) NOT NULL,
  `family` VARCHAR(45) NOT NULL,
  `origin` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `avatar` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantDB`.`user_has_plant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantDB`.`user_has_plant` ;

CREATE TABLE IF NOT EXISTS `plantDB`.`user_has_plant` (
  `user_id` INT NOT NULL,
  `plant_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `plant_id`),
  CONSTRAINT `fk_user_has_plant_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `plantDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_plant_plant1`
    FOREIGN KEY (`plant_id`)
    REFERENCES `plantDB`.`plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_has_plant_plant1_idx` ON `plantDB`.`user_has_plant` (`plant_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_plant_user_idx` ON `plantDB`.`user_has_plant` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_plant_plant1` ON `plantDB`.`user_has_plant` (`plant_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
